### ISSUE TITLE
No matter what I do, I cannot get automatic cookie detection to work.

### ISSUE THREAD

**Issue by fspy** [PoE-TradeMacro/POE-TradeMacro#177]
This is the message I get, every single time:
![](https://i.fspy.net/1483117246_452x453.png)

I can verify `cookie_data.txt` gets the correct information:
```ini
useragent=Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
cfduid=d89ea04e997c5857f9530f771902990b91482771516
cf_clearance=0e45335281dee08fd42d9772db80477582779f14-1483116576-604800
```

Doesn't matter what security setting I have on IE, if Firewall is on or off, if I use the fallback executable, and I don't use a proxy. I tried all options mentioned in the FAQ and nothing works. 

Every time I change IP's I have to manually grab cookies from Chrome.

Using git master (`3d40a7c`)

Honestly at a loss here... 😭

**Comment by kannibleklown** [comment]
same issue here, no idea what I should do to fix this, none of the fixes mentioned in the faq has worked.

**Comment by Eruyome** [comment]
I'm also at a loss... I've written down all possible solutions that I know of, I can only repeat myself over and over. Manually changing it should work though...
I'd like to automatically read chrome/firefox cookies, too, but I'll probably need help on this since I'm not experienced with c# or powershell.

**Comment by aspenglade** [comment]
I have the same problem.  Can't get things to work at all.  Not only that but when I try to set the manual settings they don't take affect in game and reloading the script wipes them out because of the auto-attempt.

I was able to get this working previously in the 1.3 script so not sure what the issue is now.

**Comment by aspenglade** [comment]
Alright, got mine working after looking on the forums.....Previously I didn't realize that when you manually set the cookies in the settings, you have to click the [Trade] OK button to save that then reload, not click the OK button on the left side.  Two different OK buttons.  Try that anyone else having issues.  Once you do it, reload the script and try in game.

**Comment by MrTastix** [comment]
Can confirm that clicking `[Trade] OK` will save the settings. The bypass works for me now, too.

**Comment by Scrlkad** [comment]
I think i found a solution to that problem.
I had same issue but after changing settings in IE it worked perfectly.
All i done was enabling scripting in IE link: https://support.microsoft.com/en-us/kb/3135465
as well Java scripting.
At the end i added poe.trade to trusted websites and the problem was solved.

**Comment by kannibleklown** [comment]
still no luck, already had the scripts active, but tried the trusted websites.

**Comment by BigCholsMD** [comment]
I am getting this issue now as well, It was literally working fine last night (1/1/2017) I have made 0 changes, and suddenly i get the same error message as OP's image

**Comment by BigCholsMD** [comment]
I was able to resolve my issue by literally manually overriding the cookies as aspenglade depicted above. I went in and manually retrieved my cookies, manually put them into the override boxes for overriding for manual cookie entry. The problem was the script isnt fetching the correct cookies. I use Chrome, and its not pulling the correct user-agent, cfduid, and cf_clearance. Its not pulling correct data for some reason, Once I went and manually looked at what the cookies are using the how to tutorial, and manually updated them, then went and manually updated them in the notepad++ file, Everything is working again. cheers, hope this helps

**Comment by Scrlkad** [comment]
@kannibleklown did you tried to access a poe.trade via IE?

**Comment by kannibleklown** [comment]
@Scrlkad yup, all is working fine, I also get  "update-check failed, Github is probably not available"  error, but i've done everything suggested and it just wont work. I get that error, and the one mentioned above. both auto detecting, and manual setting.

**Comment by BigCholsMD** [comment]
@kannibleklown are you at least able to get it to  properly display with ctrl+c in game?

**Comment by kannibleklown** [comment]
@BigCholsMD Ctrl+c works, yes. But that's not what I want it for, I want the quick price checks.

**Comment by BigCholsMD** [comment]
@kannibleklown  right, but it helps ensure the main script is in tact, its just not pulling the correct cookie data, have you ensured there is a (space) after the semi colon for the section where you put the cfduid and cf_clearance?

**Comment by BigCholsMD** [comment]
also, did you make sure you have the entire length of the string of numbers for cf_clearance? sometimes if the column width isnt wide enough, it will only copy what is visible, I ran into that issue the first go around before the auto fetch, and now the autofetch isnt properly fetching for chrome users for some reason so I had to manually get the data again

**Comment by kannibleklown** [comment]
@BigCholsMD  Not sure what you mean by a space, I don't include the semi colon , when manually doing it there's 3 separate boxes. and 100% sure i'm copying the entire cf_clearance. I've tried IE, Chrome, and Firefox. all the same results.

**Comment by BigCholsMD** [comment]
You also have to go into the TradeMacro AHS and edit it with notepad++  this file is located in \POE-TradeMacro-1.5.0\trade_data\     inside that file around line 1040ish there is a place where you can manually enter in your user agent, cfduid, and cf_clearance values, make sure you do this and save... my section looks like this for reference: 



	HttpObj.Open("POST","http://poe.trade/search")
	HttpObj.SetRequestHeader("Host","poe.trade")	
	HttpObj.SetRequestHeader("Connection","keep-alive")
	HttpObj.SetRequestHeader("Content-Length",StrLen(payload))
	HttpObj.SetRequestHeader("Cache-Control","max-age=0")
	HttpObj.SetRequestHeader("Origin","http://poe.trade")
	HttpObj.SetRequestHeader("Upgrade-Insecure-Requests","1")
	**HttpObj.SetRequestHeader("User-Agent","Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36")**
	HttpObj.SetRequestHeader("Content-type","application/x-www-form-urlencoded")
	HttpObj.SetRequestHeader("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
	HttpObj.SetRequestHeader("Referer","http://poe.trade/")
	**HttpObj.SetRequestHeader("Cookie","__cfduid=d7ff6c986808048624e4e2c352ed0f2f11482292174; cf_clearance=633db832b51c07e6408c5965c42210dcaae82401-1482357159-31536000")**
    ;HttpObj.SetRequestHeader("Accept-Encoding","gzip;q=0,deflate;q=0") ; disables compression
    ;HttpObj.SetRequestHeader("Accept-Encoding","gzip, deflate")
    ;HttpObj.SetRequestHeader("Accept-Language","en-US,en;q=0.8")    
	HttpObj.Send(payload)
	HttpObj.WaitForResponse()
	html := HttpObj.ResponseText

**Comment by kannibleklown** [comment]
HttpObj.SetRequestHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36")


HttpObj.SetRequestHeader("Cookie","__cfduid=dab35ceace9eed3027842aa29c11c3b451483226607; cf_clearance=9c957ba897ebf6c555cca2502f9210980eda6aaa-1483226612-604800")


Both lines look fine to me, 

[http://imgur.com/FMzlOGq](url)

And still the same thing.

**Comment by BigCholsMD** [comment]
hmm, if you look down further on the lines of code , check the section for currency, there is a section within that that has a place to put user agent cfdruid and cfclearance as well, see if it works, if it does you will be able to see the value of other currencies like alch orbs etc, it will tell you the chaos value from sellers

**Comment by kannibleklown** [comment]
@BigCholsMD  Assuming you mean this one, tried it and still the same thing.
	UserAgent   := TradeGlobals.Get("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36")
	cfduid      := TradeGlobals.Get("dab35ceace9eed3027842aa29c11c3b451483226607")
	cfClearance := TradeGlobals.Get("9c957ba897ebf6c555cca2502f9210980eda6aaa-1483226612-604800")

**Comment by BigCholsMD** [comment]
You are getting your values for user agent cfduid and cf clearance by doing the ctrl+shift+j and following the tutorial on where to find the values correct? and you are doing this on your main browser correct?

**Comment by kannibleklown** [comment]
@BigCholsMD Yup, here's a screen shot of it. [http://i.imgur.com/pGNcGH5.png](url)

**Comment by BigCholsMD** [comment]
go to the tab at the top that says cookies, then go to poe.trade if its listed under cookies, make sure those values for cfduid and cf clearance are the same that show in that location

**Comment by kannibleklown** [comment]
@BigCholsMD  It indeed seems so. [http://i.imgur.com/TazVwer.png](url)

**Comment by BigCholsMD** [comment]
hmm. and you have these values in the manual override within the script itself under the options and saved so that it wont try to auto fetch the values ?

**Comment by kannibleklown** [comment]
yup

**Comment by BigCholsMD** [comment]
so when you kill the script AHS, and you restart it completely, what do you see?

**Comment by kannibleklown** [comment]
If you have skype, I could screen share if that'd help at all

**Comment by BigCholsMD** [comment]
i do lemme get my headset, add djtranceplant88

**Comment by Eruyome** [comment]
@kannibleklown If you have both cloudflare bypass and update check errors you probably have another issue unrelated to cookies. Try the current [master code](https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/master.zip). This mentioned issue was fixed in https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/4a2c1ada2cda940fb5e68c0ad39553c740ceed97

**Comment by BigCholsMD** [comment]
@Eruyome  I had him screen show me his entire set up, we started clean slate, code checks in just fine, but when he runs the code its not able to check for updates with github, and even when manually pulling everything exactly as I would if it was my machine on the same browser, he still gets hung up on it not able to pull prices on ctrl d. I'm wondering if its a network issue and not a code issue?

**Comment by Eruyome** [comment]
Was this with the current master code or release version 1.5.0?

**Comment by BigCholsMD** [comment]
@Eruyome  we tried both

**Comment by kannibleklown** [comment]
@Eruyome Even when we try to ctrl +q it just parses and doesn't open the browser, he basically confirms it's a networking issue, have any ideas around that?

**Comment by orzmashi** [comment]
I have fixed the my cookies problem by disabling the antivirus software and it just go smoothly at first reqeust. 
I have Kaspersky Total-security and I think the reason lot of ppl have problem is due to the fact that with AHK tried to access website using IE-core is flagged as malware/spyware/adware by default... So figured that I would share this

**Comment by Eruyome** [comment]
@orzmashi Thx for sharing.
@kannibleklown Could you run this https://dl.dropboxusercontent.com/u/13620316/test.ahk and tell me if you get any error message?

**Comment by orzmashi** [comment]
@Eruyome It is possible to make the AHK.exe and the folder of poe script to the white list, but not all of those antivirus software works the same. I tested it that if you pass that stage, you could turn it back on and the ctrl+d works perfectly after too.

**Comment by Eruyome** [comment]
I know you can do that, but I didn't know if this is all you need to do. Can't test it (at least not without installing some other antivirus software).

**Comment by kannibleklown** [comment]
@Eruyome [imgur](http://i.imgur.com/PpLd6Ij.png) heres the error.

**Comment by Eruyome** [comment]
@kannibleklown started reading this here https://blogs.msdn.microsoft.com/jpsanders/2008/06/25/troubleshooting-code-that-uses-the-http-protocol/, anyway it seems you have some network issues. Are you sure that you're not using any proxy or have interfering antivirus software?

Could you save this as .vbs file and execuite it?

`Dim aRequest
set aRequest = CreateObject("WinHttp.WinHttpRequest.5.1")
aRequest.Open "GET","http://www.microsoft.com/",False
aRequest.Send
Wscript.Echo aRequest.responseText`

If everything is alright, you'll see the downloaded html, not sure what you'll see otherwise.

**Comment by kannibleklown** [comment]
@Eruyome [Link](http://i.imgur.com/hTF5lvj.png)

100% sure I don't have a proxy going or any antivirus/fire wall blocking it. I've disabled them all for this.

**Comment by Eruyome** [comment]
Please open a windows console and execute this:

`netsh winhttp show proxy`

Default should be "DirectAccess (no Proxyserver)."

**Comment by kannibleklown** [comment]
@Eruyome [link](http://i.imgur.com/7CsOoii.png) doesnt seem to say that, I've never installed any kind of proxy or changed any of those settings, so not sure what this means, or if it is a proxy, how it happened, or were to look.

**Comment by Eruyome** [comment]
Not sure why you have those settings, but you could try this http://superuser.com/questions/558070/how-to-turn-off-winhttp-proxy

**Comment by kannibleklown** [comment]
@Eruyome It works! I have no idea how that proxy got set, I really have never messed with anything like that. Thank you so much for the help =p

**Comment by Eruyome** [comment]
Well, no wonder it didn't work.... WinHTTP always tried to connect to the internet over your localhost :p

**Comment by kannibleklown** [comment]
@Eruyome So strange lol, no idea how that could of happened

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/FAQ This gets longer and longer by the day (Number 1). I think I'll close this issue for now, if anyone still has problems (that can't be solved with the mentioned solutions here please open an new issue.

**Comment by BigCholsMD** [comment]
called it being a network issue lol, im just not a networks guy
